apiVersion: v1
kind: Service
metadata:
  name: cobol-frontend-service
  namespace: excop
spec:
  selector:
    app: cobol-frontend
    component: frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

