apiVersion: v1
kind: ConfigMap
metadata:
  name: excop-config
  namespace: excop
data:
  API_BASE: "http://php-api-service:9000"
  TZ: "UTC"
  EXCEL_PRIMARY_HOST: "excel-primary-service"
  EXCEL_REPLICA_HOSTS: "excel-replica-0-service,excel-replica-1-service"
  EXCEL_STORAGE_PATH: "/app/storage"
  EXCEL_SHEET_NAME: "Wanted"
  CORS_ALLOWED_ORIGINS: "http://cobol-frontend-service,http://localhost:8888"
  FRONTEND_URL: "/"

